import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/page'
import Providers from "./providers";
import ThemeSwitcher from "../app/header/ThemeSwitcher";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          {/* <ThemeSwitcher /> */}
        <Header />
        {children}
        </Providers>
        </body>
    </html>
  )
}
